title = "Abhi Sharma"
baseURL = "https://asharm8.github.io/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Oceanside, CA"
email = "asharm8@gmail.com"
favicon = "/favicon.ico"
firstName = "Abhi"
lastName = "Sharma"
phone = "1-630-544-1068"
profileImage = "img/AbhiSharma.jpg"
showEducation = true
showExperience = true
showOpenSource = true
showProjects = true
showPublications = true
showQr = true
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "XX-123446-0122"

[[params.handles]]
link = "https://www.linkedin.com/in/asharma87/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/asharm8/"
name = "GitHub"

[[params.handles]]
link = "https://bitbucket.org/asharm8/"
name = "Bitbucket"

[[params.handles]]
link = "https://stackoverflow.com/users/1014877/wiseman7687"
name = "Stack Overflow"

[[params.handles]]
link = "https://keybase.io/edwardawebb"
name = "Keybase"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"